// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// YggdrasilPolicyListerExpansion allows custom methods to be added to
// YggdrasilPolicyLister.
type YggdrasilPolicyListerExpansion interface{}

// YggdrasilPolicyNamespaceListerExpansion allows custom methods to be added to
// YggdrasilPolicyNamespaceLister.
type YggdrasilPolicyNamespaceListerExpansion interface{}
