// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	yggdrasilv1alpha1 "github.com/uswitch/yggdrasil/pkg/apis/yggdrasil/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// YggdrasilPolicyLister helps list YggdrasilPolicies.
// All objects returned here must be treated as read-only.
type YggdrasilPolicyLister interface {
	// List lists all YggdrasilPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*yggdrasilv1alpha1.YggdrasilPolicy, err error)
	// YggdrasilPolicies returns an object that can list and get YggdrasilPolicies.
	YggdrasilPolicies(namespace string) YggdrasilPolicyNamespaceLister
	YggdrasilPolicyListerExpansion
}

// yggdrasilPolicyLister implements the YggdrasilPolicyLister interface.
type yggdrasilPolicyLister struct {
	listers.ResourceIndexer[*yggdrasilv1alpha1.YggdrasilPolicy]
}

// NewYggdrasilPolicyLister returns a new YggdrasilPolicyLister.
func NewYggdrasilPolicyLister(indexer cache.Indexer) YggdrasilPolicyLister {
	return &yggdrasilPolicyLister{listers.New[*yggdrasilv1alpha1.YggdrasilPolicy](indexer, yggdrasilv1alpha1.Resource("yggdrasilpolicy"))}
}

// YggdrasilPolicies returns an object that can list and get YggdrasilPolicies.
func (s *yggdrasilPolicyLister) YggdrasilPolicies(namespace string) YggdrasilPolicyNamespaceLister {
	return yggdrasilPolicyNamespaceLister{listers.NewNamespaced[*yggdrasilv1alpha1.YggdrasilPolicy](s.ResourceIndexer, namespace)}
}

// YggdrasilPolicyNamespaceLister helps list and get YggdrasilPolicies.
// All objects returned here must be treated as read-only.
type YggdrasilPolicyNamespaceLister interface {
	// List lists all YggdrasilPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*yggdrasilv1alpha1.YggdrasilPolicy, err error)
	// Get retrieves the YggdrasilPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*yggdrasilv1alpha1.YggdrasilPolicy, error)
	YggdrasilPolicyNamespaceListerExpansion
}

// yggdrasilPolicyNamespaceLister implements the YggdrasilPolicyNamespaceLister
// interface.
type yggdrasilPolicyNamespaceLister struct {
	listers.ResourceIndexer[*yggdrasilv1alpha1.YggdrasilPolicy]
}
