// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/uswitch/yggdrasil/pkg/apis/yggdrasil/v1alpha1"
	yggdrasilv1alpha1 "github.com/uswitch/yggdrasil/pkg/client/clientset/versioned/typed/yggdrasil/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeYggdrasilPolicies implements YggdrasilPolicyInterface
type fakeYggdrasilPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.YggdrasilPolicy, *v1alpha1.YggdrasilPolicyList]
	Fake *FakeYggdrasilV1alpha1
}

func newFakeYggdrasilPolicies(fake *FakeYggdrasilV1alpha1, namespace string) yggdrasilv1alpha1.YggdrasilPolicyInterface {
	return &fakeYggdrasilPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.YggdrasilPolicy, *v1alpha1.YggdrasilPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("yggdrasilpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("YggdrasilPolicy"),
			func() *v1alpha1.YggdrasilPolicy { return &v1alpha1.YggdrasilPolicy{} },
			func() *v1alpha1.YggdrasilPolicyList { return &v1alpha1.YggdrasilPolicyList{} },
			func(dst, src *v1alpha1.YggdrasilPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.YggdrasilPolicyList) []*v1alpha1.YggdrasilPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.YggdrasilPolicyList, items []*v1alpha1.YggdrasilPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
