// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/uswitch/yggdrasil/pkg/client/clientset/versioned/typed/yggdrasil/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeYggdrasilV1alpha1 struct {
	*testing.Fake
}

func (c *FakeYggdrasilV1alpha1) YggdrasilPolicies(namespace string) v1alpha1.YggdrasilPolicyInterface {
	return newFakeYggdrasilPolicies(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeYggdrasilV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
