// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisyggdrasilv1alpha1 "github.com/uswitch/yggdrasil/pkg/apis/yggdrasil/v1alpha1"
	versioned "github.com/uswitch/yggdrasil/pkg/client/clientset/versioned"
	internalinterfaces "github.com/uswitch/yggdrasil/pkg/client/informers/externalversions/internalinterfaces"
	yggdrasilv1alpha1 "github.com/uswitch/yggdrasil/pkg/client/listers/yggdrasil/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// YggdrasilPolicyInformer provides access to a shared informer and lister for
// YggdrasilPolicies.
type YggdrasilPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() yggdrasilv1alpha1.YggdrasilPolicyLister
}

type yggdrasilPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewYggdrasilPolicyInformer constructs a new informer for YggdrasilPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewYggdrasilPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredYggdrasilPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredYggdrasilPolicyInformer constructs a new informer for YggdrasilPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredYggdrasilPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.YggdrasilV1alpha1().YggdrasilPolicies(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.YggdrasilV1alpha1().YggdrasilPolicies(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.YggdrasilV1alpha1().YggdrasilPolicies(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.YggdrasilV1alpha1().YggdrasilPolicies(namespace).Watch(ctx, options)
			},
		}, client),
		&apisyggdrasilv1alpha1.YggdrasilPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *yggdrasilPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredYggdrasilPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *yggdrasilPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisyggdrasilv1alpha1.YggdrasilPolicy{}, f.defaultInformer)
}

func (f *yggdrasilPolicyInformer) Lister() yggdrasilv1alpha1.YggdrasilPolicyLister {
	return yggdrasilv1alpha1.NewYggdrasilPolicyLister(f.Informer().GetIndexer())
}
