// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	yggdrasilv1alpha1 "github.com/uswitch/yggdrasil/pkg/apis/yggdrasil/v1alpha1"
	scheme "github.com/uswitch/yggdrasil/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// YggdrasilPoliciesGetter has a method to return a YggdrasilPolicyInterface.
// A group's client should implement this interface.
type YggdrasilPoliciesGetter interface {
	YggdrasilPolicies(namespace string) YggdrasilPolicyInterface
}

// YggdrasilPolicyInterface has methods to work with YggdrasilPolicy resources.
type YggdrasilPolicyInterface interface {
	Create(ctx context.Context, yggdrasilPolicy *yggdrasilv1alpha1.YggdrasilPolicy, opts v1.CreateOptions) (*yggdrasilv1alpha1.YggdrasilPolicy, error)
	Update(ctx context.Context, yggdrasilPolicy *yggdrasilv1alpha1.YggdrasilPolicy, opts v1.UpdateOptions) (*yggdrasilv1alpha1.YggdrasilPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*yggdrasilv1alpha1.YggdrasilPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*yggdrasilv1alpha1.YggdrasilPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *yggdrasilv1alpha1.YggdrasilPolicy, err error)
	YggdrasilPolicyExpansion
}

// yggdrasilPolicies implements YggdrasilPolicyInterface
type yggdrasilPolicies struct {
	*gentype.ClientWithList[*yggdrasilv1alpha1.YggdrasilPolicy, *yggdrasilv1alpha1.YggdrasilPolicyList]
}

// newYggdrasilPolicies returns a YggdrasilPolicies
func newYggdrasilPolicies(c *YggdrasilV1alpha1Client, namespace string) *yggdrasilPolicies {
	return &yggdrasilPolicies{
		gentype.NewClientWithList[*yggdrasilv1alpha1.YggdrasilPolicy, *yggdrasilv1alpha1.YggdrasilPolicyList](
			"yggdrasilpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *yggdrasilv1alpha1.YggdrasilPolicy { return &yggdrasilv1alpha1.YggdrasilPolicy{} },
			func() *yggdrasilv1alpha1.YggdrasilPolicyList { return &yggdrasilv1alpha1.YggdrasilPolicyList{} },
		),
	}
}
